[app]
name = "FlowZwerg"
menu = "Apps"

[entry]
class = "FlowZwerg"

[metadata]
author = "deantonious"
license = "MIT"
url = "https://github.com/deantonious/flow3rzwerg"
description = "Your trusted CCCamp gnome data on your badge!"
version = 3.8
